apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: apache-test-vpa
  namespace: scale-test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-test
  updatePolicy:
    updateMode: "Auto"
